import { base } from '$app/paths';
import {
  COOKIE_PREFIX,
  JWT_COOKIE_NAME,
  CSRF_TOKEN_COOKIE_NAME,
  updateApiUrl,
  API_URL,
  updatePanoWebsiteUrl,
  updatePanoWebsiteApiUrl,
} from '$lib/variables';

import ApiUtil, { networkErrorBody } from '$lib/api.util.js';
import { internalLibsHash } from '$lib/internalLibs.js';

async function fetchBasicData(token, csrfToken) {
  return ApiUtil.get({ path: '/api/panel/basicData', token, csrfToken }).catch(
    () => networkErrorBody,
  );
}

function getCookieWithHttpFallback(cookies, baseName) {
  return cookies.get(baseName) ?? cookies.get(`${baseName}_http`);
}

function stripModulePreload(linkHeader) {
  const parts = linkHeader
    .split(',')
    .map((p) => p.trim())
    .filter(Boolean);

  const kept = parts.filter((p) => !/;\s*rel="?modulepreload"?/i.test(p));

  return kept.length ? kept.join(', ') : null;
}

const isDev = process.env.NODE_ENV === 'development';
// Content-hashed lib namespace. The hash is generated by scripts/bundle-internal-libs.js
// and embedded into the importmap, so the URL uniquely identifies the content. A `?v=`
// query string would not work — the server ignores it and would serve the current file for
// any v, which causes ABI mismatches when stale clients fetch new svelte/sdk bundles.
const libBase = `${base}/lib/${internalLibsHash}`;
const IMPORT_MAP = `
  <script type="importmap" crossorigin="anonymous">
  {
    "imports": {
      "svelte": "${isDev ? `${base}/@id/svelte` : `${libBase}/svelte/index.js`}",
      "svelte/animate": "${isDev ? `${base}/@id/svelte/animate` : `${libBase}/svelte/animate.js`}",
      "svelte/easing": "${isDev ? `${base}/@id/svelte/easing` : `${libBase}/svelte/easing.js`}",
      "svelte/motion": "${isDev ? `${base}/@id/svelte/motion` : `${libBase}/svelte/motion.js`}",
      "svelte/store": "${isDev ? `${base}/@id/svelte/store` : `${libBase}/svelte/store.js`}",
      "svelte/transition": "${isDev ? `${base}/@id/svelte/transition` : `${libBase}/svelte/transition.js`}",
      "svelte/internal": "${isDev ? `${base}/@id/svelte/internal` : `${libBase}/svelte/internal.js`}",
      "svelte/internal/client": "${isDev ? `${base}/@id/svelte/internal/client` : `${libBase}/svelte/internal-client.js`}",
      "svelte/internal/disclose-version": "${isDev ? `${base}/@id/svelte/internal/disclose-version` : `${libBase}/svelte/internal-disclose-version.js`}",
      "svelte/internal/flags/legacy": "${isDev ? `${base}/@id/svelte/internal/flags/legacy` : `${libBase}/svelte/internal-flags-legacy.js`}",
      "svelte/internal/flags/async": "${isDev ? `${base}/@id/svelte/internal/flags/async` : `${libBase}/svelte/internal-flags-async.js`}",
      "svelte/internal/flags/tracing": "${isDev ? `${base}/@id/svelte/internal/flags/tracing` : `${libBase}/svelte/internal-flags-tracing.js`}",
      "svelte/internal/server": "${isDev ? `${base}/@id/svelte/internal/server` : `${libBase}/svelte/internal-server.js`}",
      "svelte/legacy": "${isDev ? `${base}/@id/svelte/legacy` : `${libBase}/svelte/legacy.js`}",
      "svelte/events": "${isDev ? `${base}/@id/svelte/events` : `${libBase}/svelte/events.js`}",
      "svelte-i18n": "${isDev ? `${base}/@id/svelte-i18n` : `${libBase}/svelte/i18n.js`}",
      "@panomc/sdk": "${libBase}/sdk/index.js",
      "@panomc/sdk/components/theme": "${libBase}/sdk/components-theme.js",
      "@panomc/sdk/components/panel": "${libBase}/sdk/components-panel.js",
      "@panomc/sdk/toasts": "${libBase}/sdk/toasts.js",
      "@panomc/sdk/utils/api": "${libBase}/sdk/utils-api.js",
      "@panomc/sdk/utils/auth": "${libBase}/sdk/utils-auth.js",
      "@panomc/sdk/utils/tooltip": "${libBase}/sdk/utils-tooltip.js",
      "@panomc/sdk/utils/language": "${libBase}/sdk/utils-language.js",
      "@panomc/sdk/utils/component": "${libBase}/sdk/utils-component.js",
      "@panomc/sdk/utils/text": "${libBase}/sdk/utils-text.js",
      "@panomc/sdk/variables": "${libBase}/sdk/variables.js",
      "@panomc/sdk/svelte": "${libBase}/sdk/svelte.js",
      "@panomc/sdk/internal": "${libBase}/sdk/internal.js"
    }
  }
  </script>
  <script defer src="${libBase}/bootstrap/bootstrap.bundle.min.js"></script>`;
const PLACEHOLDER = '%pano_lib_import%';
const PLACEHOLDER_LEN = PLACEHOLDER.length;

/** @type {import('@sveltejs/kit').Handle} */
export async function handle({ event, resolve }) {
  const { cookies } = event;
  const locals = event.locals;

  // noinspection JSUnresolvedReference
  const apiUrlEnv = process.env.API_URL;

  // noinspection JSUnresolvedReference
  const panoWebsiteUrlEnv = process.env.PANO_WEBSITE_URL;

  // noinspection JSUnresolvedReference
  const panoWebsiteApiUrlEnv = process.env.PANO_WEBSITE_API_URL;

  if (apiUrlEnv) {
    updateApiUrl(apiUrlEnv);
    locals.apiUrlEnv = apiUrlEnv;
  }

  if (panoWebsiteUrlEnv) {
    updatePanoWebsiteUrl(panoWebsiteUrlEnv);
    locals.panoWebsiteUrlEnv = panoWebsiteUrlEnv;
  }

  if (panoWebsiteApiUrlEnv) {
    updatePanoWebsiteApiUrl(panoWebsiteApiUrlEnv);
    locals.panoWebsiteApiUrlEnv = panoWebsiteApiUrlEnv;
  }

  const jwt = getCookieWithHttpFallback(cookies, COOKIE_PREFIX + JWT_COOKIE_NAME);
  const csrfToken = getCookieWithHttpFallback(cookies, COOKIE_PREFIX + CSRF_TOKEN_COOKIE_NAME);
  locals.basicData = await fetchBasicData(jwt, csrfToken);
  locals.jwt = jwt;
  locals.csrfToken = csrfToken;

  const response = await resolve(event, {
    transformPageChunk: ({ html }) => {
      const index = html.indexOf(PLACEHOLDER);
      if (index === -1) return html;
      return html.substring(0, index) + IMPORT_MAP + html.substring(index + PLACEHOLDER_LEN);
    },
  });

  const ct = response.headers.get('content-type') || '';
  if (ct.includes('text/html')) {
    const link = response.headers.get('link');
    if (link) {
      const filtered = stripModulePreload(link);
      if (filtered) response.headers.set('link', filtered);
      else response.headers.delete('link');
    }
  }

  return response;
}

/** @type {import('@sveltejs/kit').HandleServerError} */
export function handleError({ error, event }) {
  console.log('!!! [GLOBAL ERROR EVENT]:', event.url.href);
  console.error('!!! [GLOBAL ERROR CONTENT]:', error);
  return {
    message: 'Internal Error',
    code: error?.code,
  };
}

/** @type {import('@sveltejs/kit').HandleFetch} */
export async function handleFetch({ event, request, fetch }) {
  // Rewrite relative /api/ requests to the backend URL during SSR.
  // Load functions now use relative paths for consistent SSR↔CSR fetch dedup.
  if (request.url.startsWith(event.url.origin + "/api/")) {
    const apiPath = new URL(request.url).pathname + new URL(request.url).search;
    const backendUrl = new URL(API_URL).origin + apiPath;
    request = new Request(backendUrl, request);
    request.headers.set("cookie", event.request.headers.get("cookie") || "");
    request.headers.set("Origin", API_URL);
  } else if (request.url.startsWith(API_URL)) {
    request.headers.set("cookie", event.request.headers.get("cookie") || "");
    request.headers.set("Origin", API_URL);
  }

  return fetch(request);
}
